# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('vorname', models.TextField(db_column='Vorname')),
                ('geburtsdatum', models.DateField(blank=True, db_column='Geburtsdatum', null=True)),
                ('verguenstigung', models.IntegerField(db_column='Verguenstigung')),
                ('wohnort', models.TextField(blank=True, db_column='Wohnort', null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('vorname', models.TextField(db_column='Vorname')),
                ('teilzeit', models.IntegerField(db_column='Teilzeit')),
            ],
            options={
                'db_table': 'mitarbeiter',
                'managed': False,
            },
        ),
    ]
