# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwalten', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verguenstigung',
            field=models.CharField(max_length=200),
        ),
    ]
