# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwalten', '0003_auto_20171114_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verguenstigung',
            field=models.CharField(default='Nein', max_length=200),
        ),
    ]
