# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0003_auto_20171114_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verwalten.User'),
        ),
    ]
